version: '3'
services:
  opensearch-node1:
    image: local-opensearch-learning-to-rank:latest
    container_name: opensearch-node1
    environment:
      - discovery.type=single-node
      - http.max_content_length=1000mb
      - "OPENSEARCH_JAVA_OPTS=-Xms4G -Xmx4G"
      - DISABLE_SECURITY_PLUGIN=true
    volumes:
      - opensearch-machine-learning-data:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - opensearch-net
  
  opensearch-dashboards:
    image: local-opensearch-dashboard-disabled-security:latest
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch-node1:9200"]'
    depends_on:
      - opensearch-node1
    networks:
      - opensearch-net


volumes:
  opensearch-machine-learning-data:

networks:
  opensearch-net:
    driver: bridge
